### ISSUE TITLE
Google Fonts Onboarding: QA FAIL: Copyright notices should match canonical pattern in fonts

### ISSUE THREAD

**Issue by eliheuer** [reddit/redditsans#6]
Google Fonts onboarding uses [FontBakery](https://github.com/fonttools/fontbakery) for QA. All `FAIL` level checks from the `universal`, `opentype` and `googlefonts` profiles must be passing in order to onboard fonts to Google Fonts. Exceptions can be made if necessary.

See the [Quality Assurance](https://googlefonts.github.io/gf-guide/qa.html) section of the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) for more information: https://googlefonts.github.io/gf-guide/qa.html

🔥 **FAIL: Copyright notices match canonical pattern in fonts** ([com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright))

🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright (c) 2020-21, Reddit, Inc. (https://www.reddit.com/). This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL"

**See the Google Fonts Guide for more information:** https://googlefonts.github.io/gf-guide

**Comment by stephenhutchings** [comment]
If this issue is non-critical, Reddit's preference is to leave the copyright as is.

**Comment by davelab6** [comment]
The copyright in the license file is peculiar in naming the 3 families together; eg the mono has an irrelevant notice about the condensed, the notice will change as the condensed becomes a width axis. 

It also doesn't match the notice in the font files, eg the dates are different.

I think if Reddit doesn't want to adopt the "the PROJECT NAME project authors" citation and only use `Reddit, Inc`, and will set up a CLA so that 3rd party contributions via PR to this repo don't require changing the notice, that's fine with me/Google; fixing the dates to match is trivial.

Giving the url as reddit.com isn't very helpful, IMHO, compared to this repo URL, but again I'm willing to let that go if Reddit insists.

**Comment by stephenhutchings** [comment]
Thanks @davelab6. I noticed the inconsistent years between the licence and fonts, and that should be amended in the most recent 1.012 version. All should now read 2020-2023.

For the other points, I'll pass your comments onto Reddit and get back to you.

**Comment by tr000y** [comment]
Hey @davelab6, Reddit Inc has a CLA with Google in place, does that suffice here? 

Regarding the url, we're happy to take your suggestion and link out to the repo url instead. cc @stephenhutchings
